In [6]:
import numpy as np
np.version

<module 'numpy.version' from 'C:\\Users\\Дмитрий\\AppData\\Roaming\\Python\\Python37\\site-packages\\numpy\\version.py'>

In [12]:
ordinalArray = [4,5,7,8,5,6,4,7,8,5]
npArray = np.array(ordinalArray,float)
print(ordinalArray)
print(npArray)

[4, 5, 7, 8, 5, 6, 4, 7, 8, 5]
[4. 5. 7. 8. 5. 6. 4. 7. 8. 5.]


In [13]:
print(type(ordinalArray))
print(type(npArray))

<class 'list'>
<class 'numpy.ndarray'>


In [16]:
ordinalArray2D = [[4,5,7,8,5,6,4,7,8,5],
                  [4,7,8,5,4,5,7,8,5,6],
                  [4,5,7,8,5,6,4,7,8,5],
                  [4,7,8,5,4,5,7,8,5,6],
                  [4,5,7,8,5,6,4,7,8,5],
                  [4,7,8,5,4,5,7,8,5,6],
                  [4,5,7,8,5,6,4,7,8,5],
                  [4,7,8,5,4,5,7,8,5,6],
                  [4,5,7,8,5,6,4,7,8,5],
                  [4,7,8,5,4,5,7,8,5,6]]
npArray2D = np.array(ordinalArray2D,float)
print((ordinalArray2D))
print((npArray2D))

[[4, 5, 7, 8, 5, 6, 4, 7, 8, 5], [4, 7, 8, 5, 4, 5, 7, 8, 5, 6], [4, 5, 7, 8, 5, 6, 4, 7, 8, 5], [4, 7, 8, 5, 4, 5, 7, 8, 5, 6], [4, 5, 7, 8, 5, 6, 4, 7, 8, 5], [4, 7, 8, 5, 4, 5, 7, 8, 5, 6], [4, 5, 7, 8, 5, 6, 4, 7, 8, 5], [4, 7, 8, 5, 4, 5, 7, 8, 5, 6], [4, 5, 7, 8, 5, 6, 4, 7, 8, 5], [4, 7, 8, 5, 4, 5, 7, 8, 5, 6]]
[[4. 5. 7. 8. 5. 6. 4. 7. 8. 5.]
 [4. 7. 8. 5. 4. 5. 7. 8. 5. 6.]
 [4. 5. 7. 8. 5. 6. 4. 7. 8. 5.]
 [4. 7. 8. 5. 4. 5. 7. 8. 5. 6.]
 [4. 5. 7. 8. 5. 6. 4. 7. 8. 5.]
 [4. 7. 8. 5. 4. 5. 7. 8. 5. 6.]
 [4. 5. 7. 8. 5. 6. 4. 7. 8. 5.]
 [4. 7. 8. 5. 4. 5. 7. 8. 5. 6.]
 [4. 5. 7. 8. 5. 6. 4. 7. 8. 5.]
 [4. 7. 8. 5. 4. 5. 7. 8. 5. 6.]]


In [17]:
npArray2D[:,4]

array([5., 4., 5., 4., 5., 4., 5., 4., 5., 4.])

In [19]:
npArray2D[0,:]

array([4., 5., 7., 8., 5., 6., 4., 7., 8., 5.])

In [20]:
npArray2D.shape

(10, 10)

In [21]:
npArray2D2 = np.array([[5,6,7],[4,1,2]])

In [22]:
npArray2D2.shape

(2, 3)

In [23]:
npArray2D2.dtype

dtype('int32')

In [24]:
npArray2D.dtype

dtype('float64')

In [25]:
len(npArray2D)

10

In [26]:
6 in npArray2D2

True

In [27]:
61 in npArray2D2

False

In [29]:
Array3 = [i * j for i in range(30) for j in range(0,30,4)]
print(Array3)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 8, 12, 16, 20, 24, 28, 0, 8, 16, 24, 32, 40, 48, 56, 0, 12, 24, 36, 48, 60, 72, 84, 0, 16, 32, 48, 64, 80, 96, 112, 0, 20, 40, 60, 80, 100, 120, 140, 0, 24, 48, 72, 96, 120, 144, 168, 0, 28, 56, 84, 112, 140, 168, 196, 0, 32, 64, 96, 128, 160, 192, 224, 0, 36, 72, 108, 144, 180, 216, 252, 0, 40, 80, 120, 160, 200, 240, 280, 0, 44, 88, 132, 176, 220, 264, 308, 0, 48, 96, 144, 192, 240, 288, 336, 0, 52, 104, 156, 208, 260, 312, 364, 0, 56, 112, 168, 224, 280, 336, 392, 0, 60, 120, 180, 240, 300, 360, 420, 0, 64, 128, 192, 256, 320, 384, 448, 0, 68, 136, 204, 272, 340, 408, 476, 0, 72, 144, 216, 288, 360, 432, 504, 0, 76, 152, 228, 304, 380, 456, 532, 0, 80, 160, 240, 320, 400, 480, 560, 0, 84, 168, 252, 336, 420, 504, 588, 0, 88, 176, 264, 352, 440, 528, 616, 0, 92, 184, 276, 368, 460, 552, 644, 0, 96, 192, 288, 384, 480, 576, 672, 0, 100, 200, 300, 400, 500, 600, 700, 0, 104, 208, 312, 416, 520, 624, 728, 0, 108, 216, 324, 432, 540, 648, 756, 0, 112, 224, 

In [30]:
npArray3 = np.array(Array3)
npArray3

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   4,   8,  12,  16,
        20,  24,  28,   0,   8,  16,  24,  32,  40,  48,  56,   0,  12,
        24,  36,  48,  60,  72,  84,   0,  16,  32,  48,  64,  80,  96,
       112,   0,  20,  40,  60,  80, 100, 120, 140,   0,  24,  48,  72,
        96, 120, 144, 168,   0,  28,  56,  84, 112, 140, 168, 196,   0,
        32,  64,  96, 128, 160, 192, 224,   0,  36,  72, 108, 144, 180,
       216, 252,   0,  40,  80, 120, 160, 200, 240, 280,   0,  44,  88,
       132, 176, 220, 264, 308,   0,  48,  96, 144, 192, 240, 288, 336,
         0,  52, 104, 156, 208, 260, 312, 364,   0,  56, 112, 168, 224,
       280, 336, 392,   0,  60, 120, 180, 240, 300, 360, 420,   0,  64,
       128, 192, 256, 320, 384, 448,   0,  68, 136, 204, 272, 340, 408,
       476,   0,  72, 144, 216, 288, 360, 432, 504,   0,  76, 152, 228,
       304, 380, 456, 532,   0,  80, 160, 240, 320, 400, 480, 560,   0,
        84, 168, 252, 336, 420, 504, 588,   0,  88, 176, 264, 35

In [37]:
npArray3 = npArray3.reshape((15,16))
print(npArray3)

[[  0   0   0   0   0   0   0   0   0   4   8  12  16  20  24  28]
 [  0   8  16  24  32  40  48  56   0  12  24  36  48  60  72  84]
 [  0  16  32  48  64  80  96 112   0  20  40  60  80 100 120 140]
 [  0  24  48  72  96 120 144 168   0  28  56  84 112 140 168 196]
 [  0  32  64  96 128 160 192 224   0  36  72 108 144 180 216 252]
 [  0  40  80 120 160 200 240 280   0  44  88 132 176 220 264 308]
 [  0  48  96 144 192 240 288 336   0  52 104 156 208 260 312 364]
 [  0  56 112 168 224 280 336 392   0  60 120 180 240 300 360 420]
 [  0  64 128 192 256 320 384 448   0  68 136 204 272 340 408 476]
 [  0  72 144 216 288 360 432 504   0  76 152 228 304 380 456 532]
 [  0  80 160 240 320 400 480 560   0  84 168 252 336 420 504 588]
 [  0  88 176 264 352 440 528 616   0  92 184 276 368 460 552 644]
 [  0  96 192 288 384 480 576 672   0 100 200 300 400 500 600 700]
 [  0 104 208 312 416 520 624 728   0 108 216 324 432 540 648 756]
 [  0 112 224 336 448 560 672 784   0 116 232 348 464 580 696 

In [38]:
npArray3.shape


(15, 16)

In [40]:
npArray3.fill(1)
npArray3

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [44]:
print(npArray2D2.transpose())

[[5 4]
 [6 1]
 [7 2]]


In [45]:
print(npArray2D2)

[[5 6 7]
 [4 1 2]]


In [48]:
npArray2D2[0,0] = 0

In [49]:
npArray2D2

array([[0, 6, 7],
       [4, 1, 2]])

In [50]:
print(npArray2D2.flatten())

[0 6 7 4 1 2]


In [51]:
npArray2D2

array([[0, 6, 7],
       [4, 1, 2]])

In [52]:
npArray2D3 = np.array([[4,6,7],[3,1,4]])

In [55]:
npArray2D4 = np.concatenate((npArray2D2,npArray2D3))

In [56]:
print(npArray2D4)

[[0 6 7]
 [4 1 2]
 [4 6 7]
 [3 1 4]]


In [58]:
npArray3D4 = npArray2D4[:,np.newaxis]

In [59]:
npArray3D4.shape

(4, 1, 3)

In [60]:
print(np.ones((4,4),int))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [62]:
print(np.identity(4,int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [66]:
print(np.eye(8,k=-1,dtype=int))

[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]]


In [71]:
a = np.array([1,2,3])
b = np.array([5,2,6])
a + b

array([6, 4, 9])

In [72]:
a - b

array([-4,  0, -3])

In [73]:
a * b

array([ 5,  4, 18])

In [74]:
a / b

array([0.2, 1. , 0.5])

In [75]:
a % b

array([1, 0, 3], dtype=int32)

In [76]:
a.sum()

6

In [77]:
a.prod()

6

In [78]:
b.prod()

60

In [79]:
b.sum()

13

In [80]:
b.mean()

4.333333333333333

In [81]:
b.var()

2.888888888888889

In [83]:
b.std()

1.699673171197595

In [84]:
a.max()

3

In [85]:
a.min()

1

In [86]:
a.argmax()

2

In [87]:
a.argmin()

0

In [88]:
npArray2D4

array([[0, 6, 7],
       [4, 1, 2],
       [4, 6, 7],
       [3, 1, 4]])

In [89]:
npArray2D4.max()

7

In [90]:
npArray2D4.argmax()

2

In [91]:
npArray2D4.max(axis=1)

array([7, 4, 7, 4])

In [92]:
npArray2D4.clip(0,5)

array([[0, 5, 5],
       [4, 1, 2],
       [4, 5, 5],
       [3, 1, 4]])

In [93]:
npArray2D4.clip(2,5)

array([[2, 5, 5],
       [4, 2, 2],
       [4, 5, 5],
       [3, 2, 4]])

In [94]:
npArray2D4.diagonal()

array([0, 1, 7])